### ISSUE TITLE
Typescript fails on `import { Story } from 'inkjs';` in 2.2.3 / 2.2.4

### ISSUE THREAD

**Issue by sebastian-onlea** [y-lohse/inkjs#1065]
## Describe the bug
```typescript
import { Story } from 'inkjs'; // should work!
```

... but instead...

```text
src/index.ts:1:10 - error TS2614: Module '"inkjs"' has no exported member 'Story'. Did you mean to use 'import Story from "inkjs"' instead?

1 import { Story } from 'inkjs';
           ~~~~~


Found 1 error in src/index.ts:1
```

## To Reproduce
trivial reproduction package tgz is attached (typescript and inkjs). unpack and `npm start`.
[ts-inkjs-test-1.0.0.tgz](https://github.com/user-attachments/files/15795663/ts-inkjs-test-1.0.0.tgz)

## Expected behavior
`import { Story } from 'inkjs';` works in inkjs v2.2.2.

## Environment
 - OS: MacOS 14.5
 - Node.js version: v20.12.2
 - _inklecate_ version: n/a
 - _inkjs_ version: 2.2.4

## Additional context
Is there a different way I should be importing it? `import { Story } from 'inkjs';` is still indicated in the README.md.

**Comment by martinpi** [comment]
I'm struggling with the same issue and `import ink from 'inkjs/full';` doesn't work either. Thought that would maybe be a workaround.

**Comment by martinpi** [comment]
Update. This code is marked by lint as not working (just like in this bug here) but then the compiler has no problem.

```
import ink, { Story, Compiler } from 'inkjs/full';
import { storyContent } from './story';

export type InkChoice = { text: string, index: number };
export type InkStory = InstanceType<typeof ink.Story>;
export type InkCompiler = InstanceType<typeof ink.Compiler>;

export class InkLink {
	private story: InkStory;

	constructor() {
		this.story = new Story(storyContent);
	}
}
```

**Comment by kalani96746** [comment]
let Story = Story;
let InkList = InkList;
let Compiler = Compiler;
let CompilerOptions = CompilerOptions;
let PosixFileHandler = PosixFileHandler;
let JsonFileHandler = JsonFileHandler;

export {Story, InkList, Compiler, CompilerOptions, PosixFileHandler, JsonFileHandler};

in ink.d.ts

I had to modify 2.2.2. i couldnʻt get 2.2.3 or 2.2.4 working right..

**Comment by smwhr** [comment]
This is being worked [in this PR](https://github.com/y-lohse/inkjs/pull/1072) 
If you can test this PR works for you, that would be of great help !
